site_name: MkDocs API documentation
site_description: Тестовая документация для учебных целей.
theme: material

nav:
  - Home: index.md
  - Overview: overview.md
  - About: about.md
  - Glossary: glossary.md
  - API Reference: dist/index.html
